#+TITLE: Cs
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css" />
#+PROPERTY: header-args :results output
#+OPTIONS: num:nil

* Hello World

Prints hello world to the screen.

#+begin_src python

print("Hello, world!")

#+end_src

* Exercise 11

Asks user to enter name, records user input, prints that input (name).

#+begin_src python

print('enter your name')
name = input()
print(name)

#+end_src

#+RESULTS:

* Exercise 12

1. The issue with this program is that the user can input any value that is not 'Yes' and sill get the message stating they will get wet.
2. "If it rains, you will stay dry"
3. [Discussed in question. 1]

* Exercise 13

1. "you are a woman"
2. "you are not allowed in the sixth form cafe"
3. "incorrect password"

* Exercise 14

#+begin_src python

print("what is your name?")
name = input(
if name == "Tom":
    print("hello Tom")
else:
    print("Where is Tom?")

#+end_src
#+begin_src python

print("do you like hot weather?")
ans = input()
if ans == "Yes":
    print("go to the beach")
else:
    print("Go somewhere cool on holiday... Like Finland.")

#+end_src
#+begin_src python

print("do you like milk?")
ans = input()
if ans == "Yes":
    print("That is great, it is a good source of calcium")
else:
    print()

#+end_src
#+begin_src python

print("how old are you?")
ans = int(input())
if ans >= 14:
    print("you are doing GCSEs")
elif ans < 14:
    print("you are not doing GCSEs")
    print("do you enjoy creative subjects?")
    ans2 = input()
    if ans2 == "Yes":
        print("Maybe you should think about Art or Music?")
    else:
        print("Maybe you should think about Computing?")

#+end_src

* Exercise 24
#+begin_src python

print("enter an end value")
end = int(input())

for counter in range (0,end):
    print(counter)

#+end_src

It will ask the user to enter a value. It will then print every number between 0 (including 0) and 1 less than that number.

* Exercise 25 Times tables

#+begin_src python

print("enter an end value")
num = int(input())
print("enter how many times tables do you wish for?")
max_count = int(input())
count = 0

for counter in range (0,max_count):
    print(count, "times", num, "is", (count * num))
    count += 1

#+end_src

* Exercise 26
#+begin_src python
pocketMoney = 0.01
for week in range(10):
    print("It is week ",week)
    print("You will get £ ",pocketMoney)
#+end_src

#+begin_src python
for week in range(1,26):
#+end_src

* Exercise 27

Asks the user to enter a password until it matches "thepassword".

#+begin_src python
print(“Enter your password”)
password = input()
while password != “thepassword”:
    print(“incorrect password, try again”)
    password = input()
#+end_src
#+RESULTS:

A while loops executes the instruction within the loop until a requirement is met.

* Exercise 28

#+begin_src python

print ("enter your name")
name = input ()
while name != "Tomaz":
    print("wrong name try again")
name = input()

#+end_src

#+begin_src python

totalValue = 0
newValue = 0
while totalValue < 100:
    print ("how much are you putting in your piggy bank?”)
    newValue = int(input())
    totalValue = totalValue+newValue
    newValue = 0
    print (totalValue)

#+end_src

* TODO Quiz.py

*** Example

#+begin_src python

print("Welcome to my Quiz")
score = 0

questNum=1
print("Question number",questNum)
answer=int(input("What is 2**7? "))
if answer==128:
    print("Yes!!")
    score=score+1
else:
    print("No!")

#+end_src

*** TODO Functions (W.I.P)

#+begin_src python

print("Welcome to my Quiz")
score = 0
def quiz(question_number):
    for i in range(3):
      print("-")
    print("Question number", question_number)

def qOne():
    global score
    quiz(1)
    print("What is 2**7?")
    answer=int(input())
    if answer==128:
        print("Yes!!")
        score = score + 1
    else:
        print("No!")

def qTwo():
  global score
  quiz(2)
  print("What is 5*5?")
  answer=int(input())
  if answer==25:
    print("Yes")
    score = score + 1
  else:
    print("No")

def qThree():
  global score
  quiz(3)


def gameStart():
    qOne()
    qTwo()
    qThree()

gameStart()

#+end_src


* Rock Paper Scissors Game

#+begin_src python

import random

usrScore = 0
comScore = 0
GameEnd = False

choices = ["R", "P", "S"]

def rock():
   print("""
      _______
   ---'   ____)
         (_____)
         (_____)
         (____)
   ---.__(___)
  """)

def paper():
   print("""
        _______
  ---'      ____)____
               ______)
             _______)
            _______)
  ---.__________)
  """)

def scissors():
   print("""
       _______
   ---'   ____)____
            ______)
         __________)
         (____)
   ---.__(___)
  """)



def rAs():
   rock()
   scissors()

def rAp():
   rock()
   paper()

def rAr():
   rock()
   rock()

def pAr():
   paper()
   rock()

def pAp():
   paper()
   paper()

def pAs():
   paper()
   scissors()

def sAr():
   scissors()
   rock()
def sAp():
    scissors()
    paper()

def sAs():
   scissors()
   scissors()

while GameEnd == False:

  if comScore >= 5:
   print("com win")
   GameEnd = True
  elif usrScore >= 5:
   print("usr win")
   GameEnd = True
  else:
    usrInput = input("Rock, Paper, Scissors : R, P, S")
    comInput = random.choice(choices)
    print(comInput)
    if usrInput == "R" and comInput == "R":
      rAr()
      print("draw")
    elif usrInput == "R" and comInput == "P":
      rAp()
      print("player loose")
      comScore += 1
    elif usrInput == "R" and comInput == "S":
      rAs()
      print("player win")
      usrScore += 1
    elif usrInput == "P" and comInput == "R":
      pAr()
      print("player win")
      usrScore += 1
    elif usrInput == "P" and comInput == "P":
      pAp()
      print("draw")
    elif usrInput == "P" and comInput == "S":
      pAs()
      print("player loose")
      comScore += 1
    elif usrInput == "S" and comInput == "R":
      sAr()
      print("player loose")
      comScore += 1
    elif usrInput == "S" and comInput == "P":
      sAp()
      print("player win")
      usrScore += 1
    elif usrInput == "S" and comInput == "S":
      sAs()
      print("draw")

#+end_src



* Python Extension Exercises - Part 2

** 1
Creating a program which asks the user to type in a a sort
a. Assign this value to a variable called sport.
b. If the sport is football, output "The beautiful game"
c. If the sport is ice hockey, output "The violent game"
d. If the sport is rugby, output "The game of egg chasers"
e. If the sport is basketball, output "Netball for men"
f. Else output "what sport do you like then"

#+begin_src python

sport = input("Type in a sport: ")

if sport == "football":
    print("The beautiful game")
elif sport == "ice hockey":
    print("The violent game")
elif sport == "rugby":
    print("The game of egg chasers")
elif sport == "basketball":
    print("Netball for men")
else:
    print("What sport do you like then")


#+end_src


** 2
Create a program which asks the user to input two integers (store these values in two variables called x and y) and a mathematical operator (+, -, / or *) and store this in a variable called operator.
a. IF the operator is a + symbol, output the value of x + y
b. IF the operator is a - symbol, output the value of x - y
c. IF the operator is a * symbol, output the value of x * y
d. ELSE output the value of x / y

#+begin_src python

print("enter x")
x = int(input())

print("enter y")
y = int(input())

print("enter an operator, + - * or / only")
operator = input()

if operator == "+":
    print(x, "+", y, "=", x+y)
elif operator == "-":
    print(x, "+", y, "=", x-y)
elif operator == "*":
    print(x, "*", y, "=", x*y)
elif operator == "/":
    print(x, "/", y, "=", x/y)

#+end_src


** 3
Create a program which asks the user to enter an amount in £ - store this value in a variable called amount.
a. Ask the user for a currency to exchange the amount to ($, Yen, Euros or NZ $) – store this in a variables called exchange.
b. IF the exchange variable is $ then output the amount multiplied by 1.5
c. IF the exchange variable is Yen then output the amount multiplied by 20
d. IF the exchange variable is Euros then output the amount multiplied by 1.3
e. IF the exchange variable is NZ $ then output the amount multiplied by 2
f. ELSE output “we don’t exchange this currency”

#+begin_src python

print("ENTER AMOUNT IN POUNDS")
poundValue = int(input())

print("WHICH CURRENCY DO YOU WISH TO CONVERT TO")
currency = input("ENTER Dollar, Yen, Euro, or NZ")

if currency == "Dollar":
    op = 1.5
elif currency == "Yen":
    op = 20
elif currency == "Euro":
    op = 1.3
elif currency == "NZ":
    op = 2
else:
    print("We don't trade this currency")


print("YOUR NEW BALANCE IS: ", poundValue * op)



#+end_src


** TODO RUST
